[package]
name = "libtiff-rs-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[build-dependencies]
cc = "1"

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.libtiff-rs]
path = ".."

[[bin]]
name = "differential"
path = "fuzz_targets/differential.rs"
test = false
doc = false
bench = false

[[bin]]
name = "differential_dir"
path = "fuzz_targets/differential_dir.rs"
test = false
doc = false
bench = false

[[bin]]
name = "differential_dir2"
path = "fuzz_targets/differential_dir2.rs"
test = false
doc = false
bench = false

[[bin]]
name = "differential_dir3"
path = "fuzz_targets/differential_dir3.rs"
